name             'fp-play-cookbooks'
maintainer       'Fuel Powered'
maintainer_email 'developer@fuelpowered.com'
license          'All rights reserved'
description      'Installs/Configures app'
long_description 'Installs/Configures app'
version          '0.1.0'
